### Test Inscription Utilisateur
POST http://ecoride.local/api/register.php
Content-Type: application/json

{
    "username": "testuser_php1",
    "firstName": "Test",
    "lastName": "PHP",
    "email": "testphp1@example.com",
    "password": "securePassword123",
    "birthdate": "1995-05-15",
    "phone": "0600000011"
}

### Test Connexion Utilisateur (Succès)
POST http://ecoride.local/api/login.php
Content-Type: application/json

{
    "identifier": "bob_passenger", 
    "password": "password123" 
}

### Test Connexion Utilisateur (Succès)
POST http://ecoride.local/api/login.php
Content-Type: application/json

{
    "identifier": "alice_driver_passenger", 
    "password": "password123" 
}

### Test Connexion Utilisateur (Admin - Succès)
POST http://ecoride.local/api/login.php
Content-Type: application/json

{
    "identifier": "admin@ecoride.com",
    "password": "adminPass"
}

### Test Connexion Utilisateur (Échec - mauvais mot de passe)
POST http://ecoride.local/api/login.php
Content-Type: application/json

{
    "identifier": "bob_passenger",
    "password": "wrongpassword"
}

### Test Connexion Utilisateur (Échec - utilisateur inconnu)
POST http://ecoride.local/api/login.php
Content-Type: application/json

{
    "identifier": "unknown_user",
    "password": "password123"
}

### Test Déconnexion Utilisateur
POST http://ecoride.local/api/logout.php
Content-Type: application/json

### Test de récupération de profil utilisateur 
GET http://ecoride.local/api/account.php 